### ISSUE TITLE
KokeshGOD

### ISSUE THREAD

**Issue by JohnDoel337** [East-Showdown/East-Showdown#118]
1) Гой создан чтобы быть нагретым 
2) Не нагреешь гоя ты, его нагреет другой, а значит ты сам станешь гоем. 
3) Не потратил - значит заработал 
4) Лучше с умным потерять, чем с гоем найти. 
5) Путь к богатству начинается не с мышления, а с прогрева первого гоя 
6) Окружение гоев сделает и тебя гоем

**Comment by danxdragon123** [comment]
Нагрів себе🤡🇷🇺🐖
