### ISSUE TITLE
Senator

### ISSUE THREAD

**Issue by JohnDoel337** [East-Showdown/East-Showdown#119]
Они ж понимают, что они будут уничтожены🔥🔥🔥, мы танками приедем🛣🛣🛣 и повесим вот этот вот флаг🇷🇺, я лично привезу😎🚔 в Киев🏙 этот флаг, я повешу его на здание Верховной рады🏢 Украины🇺🇦, крикну: "Киев наш🏙👊🏻😠🇷🇺, блять, вы все‍👨🏼🇺🇦👨🏻🇺🇦👩🏻🇺🇦👱🏻‍♀️, все сосать!!!"🖕🏻🖕🏻🖕🏻 Вы выйдете с хлебом-солью🚶‍♂️🚶‍♀️🍞🧂, с рушниками, блять, с нашими, украинско-русскими🇺🇦🤝🏻🇷🇺, вы придёте, блять, с хлебом-солью нас встречать😎🇷🇺😎, мы будем там тудаа-сюдаа➡️⬅️, хохлы🇺🇦, сосать🖕🏻, теперь вы русские🇺🇦➡️🇷🇺 все, ахахахаххаха😂😂😂, все идите сюда👈🏻. Мы заберём всю вашу территорию😏🗺, всю🤫, до клочка земли⚠️, у каждого последнего🥰. И Львов будет наш🏙🇺🇦 и Донбасс ты нам отдашь тем более🔝✅. Z, Z, Z, Z, ZZZ, ZZZZ, блять😡, это Z, это Z, это победа🎉🎊🎆🎇, это... бляяять😡😡😡, V, V, 🅾️🅾️🅾️, менi повезло😆, своих блять не бросаем😈👊🏻🤙🏻🇷🇺, всё правильно👍🏻, всё так☝🏻, надо-надо😁

**Comment by danxdragon123** [comment]
Даун
