### ISSUE TITLE
Историчность названий подразделений и их наличие

### ISSUE THREAD

**Issue by Conteyner** [East-Showdown/East-Showdown#48]
В нашем моде присутствует много погрешностей с историчностью дивизий. Человек говорил об этом ещё с августа, но видимо додумался найти моё лс только сейчас.  
![изображение](https://github.com/East-Showdown/East-Showdown/assets/122826855/6cd6f366-2ee0-47e7-a40b-d39a6fd3820d)
![изображение](https://github.com/East-Showdown/East-Showdown/assets/122826855/340c18e6-9c2b-40e9-89c1-5c8e50a35f60)

В связи с этим предлагаю перенести обновление на конец сентября, что бы я мог ознакомиться и реализовать его предложения.  Как раз сможем внести больше изменений , что поможет оправдать столь долгое ожидания обновления. 
@N1delak  @Camilot1 @Tllya  @DivineCat2281 

Кстати может предложим ему стать частью команды, так как такие графоманы нам нужны
Документы прикреплённые им :
[AFRFEast_Showdown_byWsReadyHate(1).xlsx](https://github.com/East-Showdown/East-Showdown/files/12643435/AFRFEast_Showdown_byWsReadyHate.1.xlsx)
[DPR-x-LPR_East_Showdown_byWsReadyHate.xlsx](https://github.com/East-Showdown/East-Showdown/files/12643437/DPR-x-LPR_East_Showdown_byWsReadyHate.xlsx)
[NewAFU-Brigades_byWsReadyHate.xlsx](https://github.com/East-Showdown/East-Showdown/files/12643438/NewAFU-Brigades_byWsReadyHate.xlsx)
[NGU_EastShowdown_byWsReadyHate.xlsx](https://github.com/East-Showdown/East-Showdown/files/12643439/NGU_EastShowdown_byWsReadyHate.xlsx)
[east_showdown.txt](https://github.com/East-Showdown/East-Showdown/files/12643440/east_showdown.txt)

**Comment by Conteyner** [comment]
дэм, без комментариев 
![изображение](https://github.com/East-Showdown/East-Showdown/assets/122826855/572c6a7b-189c-4cd0-b9e7-8f5cbe132971)
![изображение](https://github.com/East-Showdown/East-Showdown/assets/122826855/c69da5ac-d2f0-4340-b6e5-7ae85a0b441a) 
@Tllya  можешь пофиксить?

**Comment by Glovyss** [comment]
баzа!

**Comment by Conteyner** [comment]
не база а пиздец((

**Comment by Conteyner** [comment]
ну процентов 70 уже сделал

**Comment by Conteyner** [comment]
правда надо что бы егор иконки подправил эээ @N1delak
